export const SANPHAM_REQUESTED = 'SANPHAM_REQUESTED';
export const SANPHAM_SUCCEED = 'SANPHAM_SUCCEED';
export const SANPHAM_FAILED = 'SANPHAM_FAILED';

export const CTSANPHAM_REQUESTED = 'CTSANPHAM_REQUESTED';
export const CTSANPHAM_SUCCEED = 'CTSANPHAM_SUCCEED';
export const CTSANPHAM_FAILED = 'CTSANPHAM_FAILED';

export const DANHMUC_REQUESTED = 'DANHMUC_REQUESTED';
export const DANHMUC_SUCCEED = 'DANHMUC_SUCCEED';
export const DANHMUC_FAILED = 'DANHMUC_FAILED';

export const CTDANHMUC_REQUESTED = 'CTDANHMUC_REQUESTED';
export const CTDANHMUC_SUCCEED = 'CTDANHMUC_SUCCEED';
export const CTDANHMUC_FAILED = 'CTDANHMUC_FAILED';

export const DANGKY_REQUESTED = 'DANGKY_REQUESTED';
export const DANGKY_SUCCEED = 'DANGKY_SUCCEED';
export const DANGKY_FAILED = 'DANGKY_FAILED';

export const DANGNHAP_REQUESTED = 'DANGNHAP_REQUESTED';
export const DANGNHAP_SUCCEED = 'DANGNHAP_SUCCEED';
export const DANGNHAP_FAILED = 'DANGNHAP_FAILED';
export const CHECK_LOGIN = 'CHECK_LOGIN';

export const SPTHEODM_REQUESTED = 'SPTHEODM_REQUESTED';
export const SPTHEODM_SUCCEED = 'SPTHEODM_SUCCEED';
export const SPTHEODM_FAILED = 'SPTHEODM_FAILED';

export const GIOHANG_REQUESTED = 'GIOHANG_REQUESTED';
export const GIOHANG_SUCCEED = 'GIOHANG_SUCCEED';
export const GIOHANG_FAILED = 'GIOHANG_FAILED';

export const THEMGIOHANG_REQUESTED = 'THEMGIOHANG_REQUESTED';
export const THEMGIOHANG_SUCCEED = 'THEMGIOHANG_SUCCEED';
export const THEMGIOHANG_FAILED = 'THEMGIOHANG_FAILED';

export const XOAGIOHANG_REQUESTED = 'XOAGIOHANG_REQUESTED';
export const XOAGIOHANG_SUCCEED = 'XOAGIOHANG_SUCCEED';
export const XOAGIOHANG_FAILED = 'XOAGIOHANG_FAILED';

export const XOAALLGIOHANG_REQUESTED = 'XOAALLGIOHANG_REQUESTED';
export const XOAALLGIOHANG_SUCCEED = 'XOAALLGIOHANG_SUCCEED';
export const XOAALLGIOHANG_FAILED = 'XOAALLGIOHANG_FAILED';

export const HOADON_REQUESTED = 'HOADON_REQUESTED';
export const HOADON_SUCCEED = 'HOADON_SUCCEED';
export const HOADON_FAILED = 'HOADON_FAILED';

export const HOADON_RESETED = 'HOADON_RESETED';

export const THONGTIN_REQUESTED = 'THONGTIN_REQUESTED';
export const THONGTIN_SUCCEED = 'THONGTIN_SUCCEED';
export const THONGTIN_FAILED = 'THONGTIN_FAILED';
